[package]
name = "blockstack-core"
version = "0.0.1"
authors = ["Jude Nelson <jude@blockstack.com>", "Aaron Blankstein <aaron@blockstack.com>"]
license = "GPLv3"
homepage = "https://github.com/blockstack/blockstack-core"
repository = "https://github.com/blockstack/blockstack-core"
description = "Reference implementation of Blockstack Core"
keywords = [ "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"

[features]
developer-mode = []
default = ["developer-mode"]

[dependencies]
bitcoin = "0.14.2"
jsonrpc = "0.10.2"
rust-ini = "0.13"
rand = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1.0"
rust-crypto = "0.2" 
sha2 = "0.8.0"
dirs = "1.0.4"
regex = "1"
linefeed = "0.6"
getopts = "0.2"

[dependencies.secp256k1]
version = "0.11.5"
features = ["serde"]

[dependencies.rusqlite]
version = "0.16.0"
features = ["i128_blob", "bundled"]

[dependencies.ed25519-dalek]
version = "=1.0.0-pre.1"
features = ["serde"]

[dependencies.curve25519-dalek]
version = "=1.0.3"
features = ["serde"]

