version: 2
jobs:
  deploy:
    working_directory: /build
    docker:
      - image: rust:1.34-stretch
    steps:
      - checkout
      - run:
          command: |
            bash build-scripts/start-builds.sh
      - store_artifacts:
          path: /build/target/x86_64-apple-darwin/release/blockstack-core
          destination: macos-x64/blockstack-core
      - store_artifacts:
          path: /build/target/x86_64-pc-windows-gnu/release/blockstack-core.exe
          destination: windows-x64/blockstack-core.exe
      - store_artifacts:
          path: /build/target/x86_64-unknown-linux-gnu/release/blockstack-core
          destination: linux-x64/blockstack-core
      - store_artifacts:
          path: /build/target/x86_64-unknown-linux-musl/release/blockstack-core
          destination: linux-musl-x64/blockstack-core
  build:
    working_directory: ~/blockstack
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          command: |
            cargo build
      - run:
          environment:
            RUST_BACKTRACE: 1
            BLOCKSTACK_DEBUG: 1
            RUSTFLAGS: -Clink-dead-code
          command: |
            cargo test
#            cargo kcov && bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: feature/dist-build-scripts
      - deploy:
          filters:
            branches:
              only: feature/dist-build-scripts
